### ISSUE TITLE
Error when trying to load witness

### ISSUE THREAD

**Issue by TheReturnOfJan** [nervosnetwork/ckb-tool#2]
When I attempt to load  a witness in my script (using capsule), like so:
```
let witness_args = load_witness_args(0, Source::Input)?;
```
and use it my tests, like so:
```
// things above
    let witnesses = vec![Bytes::new(); 1];

    // build transaction
    let tx = TransactionBuilder::default()
        .input(input)
        .outputs(outputs)
        .outputs_data(outputs_data.pack())
        .witnesses(witnesses.pack())
        .cell_dep(lock_script_dep)
        .build();
    let tx = context.complete_tx(tx);
    let cycles = context
        .verify_tx(&tx, MAX_CYCLES)
        .expect("pass verification");
```
I get a runtime error when trying to load the witness, specifically:
```
thread 'tests::test_basic' panicked at 'pass verification: Error { kind: ValidationFailure(4)
```

Am I using the tool incorrectly, or is this a bug?

**Comment by jjyr** [comment]
The returned error code depends on your contract. You can use `debug!` to output debugging messages.

**Comment by TheReturnOfJan** [comment]
I am pretty sure it fails here: https://github.com/jjyr/ckb-std/blob/b49e6703914de879ca3cbc93924b22d7b519b345/src/high_level.rs#L150

Not sure what the reason could be though.

**Comment by jjyr** [comment]
The function `load_witness_args` try to parse the content of the witness into the `WitnessArgs` structure, the Encoding error is returned since your witness is empty bytes.

To load an unstructured witness you need to use `syscall::load_witness` https://nervosnetwork.github.io/ckb-std/riscv64imac-unknown-none-elf/doc/ckb_std/syscalls/fn.load_witness.html

WitnessArgs: https://docs.nervos.org/docs/essays/rules#witness

**Comment by TheReturnOfJan** [comment]
That makes sense. Thanks again 👍 (I am zceejkr on DIscord). Slowly, but surely, I am getting the hang of Nervos, and you have been very helpful 😄
